/**
 * TaskService
 * TaskService 服务
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/weicracker/swagger-yaml-to-d.ts
 * Do not edit the class manually.
 */
 declare namespace task {

    interface testInterface{
                //测试接口
            'jiwei': string;
    }

    class TaskService {
            public getMyTasks(now?: string):obs.Observable<UserApi.JsonResultSXLOfCurUserInfoVO>;
    }
 }